package io.github.expo.kolibri.compiler.ir

import io.github.expo.kolibri.compiler.fir.NativePointerStubGenerator
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irGetField
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.builders.irTemporary
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrField
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.types.classifierOrNull
import org.jetbrains.kotlin.ir.types.isLong
import org.jetbrains.kotlin.ir.util.hasAnnotation
import org.jetbrains.kotlin.ir.util.properties
import org.jetbrains.kotlin.ir.util.superClass
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * Rewrites every `@NativeMethod`-annotated method into a delegate to the native overload generated by
 * [NativePointerStubGenerator]. Given a user method `foo(args): R` and the generated native overload
 * `private external fun foo(pointer: Long, args): R`, the original `foo` loses its `external` flag and
 * gains the body `return foo(nativePointer, args)` (calling the `(J…)` overload).
 *
 * The `nativePointer` field is a plain `Long` (see [NativeObject], which stores the raw address that
 * way), so the stub — and the JNI binding — stay on a raw `long`.
 */
class NativePointerIrTransformer(private val context: IrPluginContext) : IrVisitorVoid() {
  private val nativeMethodClassId = ClassId.topLevel(FqName("io.github.expo.kolibri.NativeMethod"))
  private val asNativePointerClassId = ClassId.topLevel(FqName("io.github.expo.kolibri.AsNativePointer"))

  // `nativePointerOf(obj): Long` extracts a handle argument's pointer (null-safe).
  private val nativePointerOf by lazy {
    context.referenceFunctions(
      CallableId(FqName("io.github.expo.kolibri"), Name.identifier("nativePointerOf")),
    ).single()
  }

  // `reachabilityFenceOf(obj)` keeps a handle alive until the delegated native call returns.
  private val reachabilityFenceOf by lazy {
    context.referenceFunctions(
      CallableId(FqName("io.github.expo.kolibri"), Name.identifier("reachabilityFenceOf")),
    ).single()
  }

  override fun visitElement(element: IrElement) {
    element.acceptChildrenVoid(this)
  }

  override fun visitClass(declaration: IrClass) {
    val functions = declaration.declarations.filterIsInstance<IrSimpleFunction>()
    // The field may be declared here or inherited from a base class (e.g. NativeObject).
    val pointerField by lazy { declaration.findPointerField() }

    for (original in functions) {
      if (!original.hasAnnotation(nativeMethodClassId)) continue
      // Inherited @NativeMethod members appear here as fake overrides (already transformed in the
      // class that declares them); only declarations of this class are rewritten.
      if (original.isFakeOverride) continue
      require(original.isExternal) {
        "@NativeMethod ${declaration.name}.${original.name} must be declared `external` — " +
          "it has a body, which the plugin would otherwise replace with the native delegate"
      }
      val field = requireNotNull(pointerField) {
        "@NativeMethod ${original.name} in ${declaration.name} requires a `nativePointer` field " +
          "(declare one or extend io.github.expo.kolibri.NativeObject)"
      }
      // The stub is the overload generated by NativePointerStubGenerator for this exact original:
      // matched by plugin origin and by the lowered parameter list, so user-written overloads (or a
      // sibling original's stub) can never be picked up by accident.
      val stub = functions.firstOrNull { it.isStubFor(original) }
        ?: error(
          "@NativeMethod ${declaration.name}.${original.name}: the generated native overload is " +
            "missing — the kolibri FIR plugin did not run over this class"
        )
      val thisParam = requireNotNull(original.dispatchReceiverParameter) {
        "@NativeMethod ${original.name} must be an instance method"
      }
      val originalParams = original.regularParameters
      // The stub's regular parameters are the pointer followed by the original's, in order.
      val stubParams = stub.regularParameters

      // Handle args cross as raw pointers, so each one must be fenced after the call (see
      // [reachabilityFenceOf]); collect them up front to pick the body shape.
      val fencedParams = originalParams.filter { it.hasAnnotation(asNativePointerClassId) }

      // The stub stays native; the original becomes a plain delegate that hands it the raw pointer.
      original.isExternal = false
      val builder = DeclarationIrBuilder(context, original.symbol)
      original.body = builder.irBlockBody {
        val delegateCall = irCall(stub.symbol).apply {
          arguments[requireNotNull(stub.dispatchReceiverParameter)] = irGet(thisParam)
          arguments[stubParams[0]] = irGetField(irGet(thisParam), field)
          originalParams.forEachIndexed { index, param ->
            // An @AsNativePointer handle is passed as its Long pointer; other args pass through.
            arguments[stubParams[index + 1]] = if (param.hasAnnotation(asNativePointerClassId)) {
              irCall(nativePointerOf).apply { arguments[0] = irGet(param) }
            } else {
              irGet(param)
            }
          }
        }
        if (fencedParams.isEmpty()) {
          +irReturn(delegateCall)
        } else {
          val result = irTemporary(delegateCall)
          for (param in fencedParams) {
            +irCall(reachabilityFenceOf).apply { arguments[0] = irGet(param) }
          }
          +irReturn(irGet(result))
        }
      }
    }

    declaration.acceptChildrenVoid(this)
  }

  /**
   * Whether this function is the stub [NativePointerStubGenerator] generated for [original]: a
   * plugin-origin declaration with the same name whose parameters are `Long` (the pointer) followed
   * by the original's parameters with `@AsNativePointer` handles lowered to `Long`. The full
   * parameter-list check disambiguates between the stubs of same-name annotated overloads.
   */
  private fun IrSimpleFunction.isStubFor(original: IrSimpleFunction): Boolean {
    if ((origin as? IrDeclarationOrigin.GeneratedByPlugin)?.pluginKey != NativePointerStubGenerator.Key) {
      return false
    }
    if (name != original.name) {
      return false
    }
    
    val stubParams = regularParameters
    val originalParams = original.regularParameters

    if (stubParams.size != originalParams.size + 1) {
      return false
    }
    if (!stubParams[0].type.isLong()) {
      return false
    }

    return originalParams.withIndex().all { (index, param) ->
      val stubParam = stubParams[index + 1]
      if (param.hasAnnotation(asNativePointerClassId)) {
        stubParam.type.isLong()
      } else {
        stubParam.type.classifierOrNull == param.type.classifierOrNull
      }
    }
  }

  /** The declared (non-receiver, non-context) parameters, in declaration order. */
  private val IrFunction.regularParameters: List<IrValueParameter>
    get() = parameters.filter { it.kind == IrParameterKind.Regular }

  /** Finds the `nativePointer` backing field on this class or any of its superclasses. */
  private fun IrClass.findPointerField(): IrField? {
    var current: IrClass? = this
    while (current != null) {
      current.properties.firstOrNull { it.name.asString() == "nativePointer" }?.backingField
        ?.let { return it }
      current = current.superClass
    }
    return null
  }
}
